name: parcours_flutter_example
description: Exemple de connexion Flutter -> Laravel pour Parcours.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

flutter:
  uses-material-design: true
